name: DevOps CI/CD & Security Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # ==========================================
  # JOB 1: Security Scan & Linting (CI)
  # ==========================================
  security-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Dockerfile Syntax (Hadolint)
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
        continue-on-error: true

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'

  # ==========================================
  # JOB 2: Real Auto-Deploy Direct On Server (CD)
  # ==========================================
  deploy:
    needs: security-and-lint
    runs-on: self-hosted  # <--- Guna Self-Hosted Runner 'nabil-server'
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout Code Direct On Server
        uses: actions/checkout@v4

      - name: Deploy Docker Compose
        run: |
          set -e
          # Pergi terus ke path sebenar (Absolute Path)
          if [ -d "/root/project1" ]; then
            cd /root/project1
          elif [ -d "/root/devops/project1" ]; then
            cd /root/devops/project1
          else
            echo "Folder projek tidak dijumpai!" && exit 1
          fi
          
          git fetch --all
          git reset --hard origin/main
          docker compose up -d --build
          docker image prune -f